# Generated by Django 4.1.3 on 2022-11-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='detail',
            field=models.TextField(blank=True),
        ),
    ]
